services:
  postgres-db:
    image: postgres:16-alpine
    container_name: bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres009
      POSTGRES_DB: bank_db
    ports:
      - "5433:5432" # Exposed on 5433 to avoid conflict with any local PostgreSQL on 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  banking-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-api-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres009@postgres-db:5432/bank_db?sslmode=disable
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data:
